version: "3.9"
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
        - "5432:5432"
    volumes:
        - ./data:/var/lib/postgresql/data