vaadin:
  launch-browser: 'true'
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      additional-exclude: dev/hilla/openapi.json
  mustache:
    check-template-location: 'false'
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        show_sql: 'true'
    defer-datasource-initialization: true
logging:
  level:
    org:
      atmosphere: warn
server:
  port: ${PORT:8080}
